[package]
name = "yuka-native"
version = "0.1.0"
authors = ["Akihiro <at.sisy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdnative = "0.9.3"

[lib]
crate-type = ["cdylib"]